# Generated by Django 3.1.4 on 2021-01-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='desc',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
