# Generated by Django 3.1.4 on 2021-01-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210106_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist',
            new_name='listings',
        ),
    ]
