# Generated by Django 3.1.4 on 2021-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
