# Generated by Django 3.1.4 on 2021-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
