# Generated by Django 3.1.4 on 2021-01-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_date',
        ),
    ]
