# Generated by Django 3.1.4 on 2021-01-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210107_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
