# Generated by Django 3.1.4 on 2021-01-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210112_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
